### ISSUE TITLE
Browser not supported message

### ISSUE THREAD

**Issue by wfortin** [vitorgalvao/appear.in#4]
I have the message: "This browser is not supported" when opening the app.
![image](https://cloud.githubusercontent.com/assets/2165256/21315725/8067c83a-c5cb-11e6-8cda-23ac32f5db61.png)

**Comment by vitorgalvao** [comment]
Thank you for the report. I’ve made some tests (both with this and other apps), and it seems the current Electron version is using Chrome 50, which is behind the latest stable.

It also seems like the appear.in is blocking browsers not at their latest releases (can you confirm, @dagingaa?).

We could possibly fake the user agent, but that seems like a crummy solution. Two good possibilities, here:

+ The appear.in website (or the library they’re using, if any) allows slightly older Chrome versions.
+ We wait for Electron to update its Chrome.

**Comment by vitorgalvao** [comment]
This started working again.
