### ISSUE TITLE
Add support for screen sharing

### ISSUE THREAD

**Issue by marcosdecarvalho** [vitorgalvao/appear.in#6]
Screen sharing is a useful feature of appear.in and is handled through an Chrome extension. Is it possible to add an extension in Electron?

(Congrats on the project.)

**Comment by vitorgalvao** [comment]
> Is it possible to add an extension in Electron?

It is not, unfortunately, and [chances are it will never be](https://github.com/electron/electron/issues/1498#issuecomment-96995155). This is something I’d like as well.

> Congrats on the project.

Thank you.
